[package]
name = "othello"
version = "0.1.0"
authors = ["Robbie Ostrow <ostrowr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
lazy_static = "1.4.0"
